### ISSUE TITLE
Account.java from original p2p solanaj client

### ISSUE THREAD

**Issue by Sankalpanthi** [paymennt/solanaj#1]
Hey you have removed the Account.java file from the original p2p client so how will the Account class work?

**Comment by AbdullahAsendar** [comment]
@Sankalpanthi it was just renamed to [SolanaAccount](https://github.com/paymennt/solanaj/blob/master/src/main/java/com/paymennt/solanaj/data/SolanaAccount.java)

**Comment by Sankalpanthi** [comment]
> @Sankalpanthi it was just renamed to [SolanaAccount](https://github.com/paymennt/solanaj/blob/master/src/main/java/com/paymennt/solanaj/data/SolanaAccount.java)

And what about the DerivationPath class. Actually I am new to this, sorry if I am bothering you but can I contact you as I wish to create a solana android app to develop solana usecase and I wish to use your repo. It would be greatly appreciated.

**Comment by AbdullahAsendar** [comment]
@Sankalpanthi no worries at all, always glad to help. 

The docs are outdated, I will update the docs and ping you,

For DerivationPath, we changed the logic, check [SolanaWallet](https://github.com/paymennt/solanaj/blob/master/src/main/java/com/paymennt/solanaj/wallet/SolanaWallet.java) it will give you a good idea.

**Comment by Sankalpanthi** [comment]
Okay thanks a lot buddy

**Comment by AbdullahAsendar** [comment]
@Sankalpanthi I updated the docs, if you still need some help you can email me at abdullah@paymennt.com

**Comment by Sankalpanthi** [comment]
Thanks a lot buddy. I have mailed you a request . Please check it out whenever you are free.
